# Generated by Django 2.0.4 on 2018-04-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagement', '0002_vehicle_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='car',
            new_name='journey_id',
        ),
    ]
