# Generated by Django 2.0.4 on 2018-04-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagement', '0003_auto_20180425_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='car',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='journey_id',
            new_name='journey',
        ),
    ]
