language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

before_script:
  - mkdir -p ~/.ssh
  - echo ${SSH_PRIVATE_KEY} | base64 -d > ~/.ssh/id_rsa
  - chmod go-rwx ~/.ssh/id_rsa

script:
  - python manage.py test
  - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22022 www-data@labs.safefleet.eu cd labs-server; git pull
