language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

before_script:
  - mkdir -p ~/.ssh
  - echo ${SSH_PRIVATE_KEY} | base64 -d > ~/.ssh/id_rsa
  - ssh www-data@labs.safefleet.eu -p 22022 ls /var/www

script:
  - python manage.py test
